const config = {
  Authorization: 'Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIyNzM1MWVlZjU4MmRjODRjNmZjMTdkMTVjN2Q1ZjQ0NSIsInN1YiI6IjY2NDAyNTQwOTM2OWJiNmU2NTIwMzg5MiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.2_g9mjUwn6IU2zyAsXws_J2S4dbafz3sj5lz-OumHag',
}